### ISSUE TITLE
"RUN  apt-get" in Docker file gives error: "unknown instruction APT-GET"

### ISSUE THREAD

**Issue by amararjun** [AxisCommunications/acap-computer-vision-sdk-examples#129]
> **Please do not disclose security vulnerabilities as issues. See our [security policy](../../SECURITY.md) for responsible disclosures.**

### Describe the bug
While trying "opencv-image-capture-cpp" and " parameter-api" the docker build gives an error

docker build --tag $APP_NAME --build-arg ARCH .
```
Sending build context to Docker daemon  17.92kB
Error response from daemon: dockerfile parse error line 15: unknown instruction: APT-GET
```
### To reproduce

docker build --tag $APP_NAME --build-arg ARCH .

### Environment

- Axis device model: Q1656 LE
- Axis device firmware version: 10.12.114
- Stack trace or logs: [e.g. Axis device system logs]
- OS and version:  Ubuntu 20.04 LTS, 
- Version: SDK 1.5

**Comment by Corallo** [comment]
You are probably using an old version of docker that doesn't have buildkit enabled by default.
You can try to add `DOCKER_BUILDKIT=1` in front of your docker build command

**Comment by Corallo** [comment]
Also, to avoid further problems, update your firmware to the latest version. The 1.5 version of the sdk have a breaking change. It won't work with fw lower than 11.0

**Comment by amararjun** [comment]
@Corallo Thank you for ,as always, the prompt reply. It solved the two errors I encountered.
