### ISSUE TITLE
GLIBC_2.34' not found (required by /host/lib/liblarod.so.1) error with Q1615 MK III (AXIS OS version 10.11.65)

### ISSUE THREAD

**Issue by axisvivek** [AxisCommunications/acap-computer-vision-sdk-examples#28]
### Describe the bug

pose-estimator-with-flask example not working with Q1615 MM III (AXIS OS version 10.11.65)

### To reproduce

Follow the readme file from this project
_$ export ARCH=armv7hf
$ export CHIP=tpu
$ export AXIS_TARGET_IP=192.168.50.114
$ export DOCKER_PORT=2375
$ export APP_NAME=acap4-pose-estimator-python
$ export MODEL_NAME=acap-dl-models
$ docker -H tcp://$AXIS_TARGET_IP:$DOCKER_PORT system prune -af
$ docker build . -t $APP_NAME --build-arg ARCH
$ docker save $APP_NAME | docker -H tcp://$AXIS_TARGET_IP:$DOCKER_PORT load
$ docker build . -f Dockerfile.model -t $MODEL_NAME --build-arg ARCH
$ docker save $MODEL_NAME | docker -H tcp://$AXIS_TARGET_IP:$DOCKER_PORT load
$ docker-compose -H tcp://$AXIS_TARGET_IP:$DOCKER_PORT --env-file ./config/env.$ARCH.$CHIP up_

### Screenshots

![image](https://user-images.githubusercontent.com/52032125/167829677-18ae3008-b712-4593-af4f-9108c3efebb8.png)

Same error with minimal-ml-inference example:

![image](https://user-images.githubusercontent.com/52032125/167842242-f6ee59d4-4e3c-41b5-9228-2550ca4299ac.png)
Same error with object-detector-cpp:
![image](https://user-images.githubusercontent.com/52032125/167844158-ee3682ca-bdbd-482b-9dfe-53ae2d6f34f6.png)

### Environment

- Axis device model: [Q1615 Mk III]
- Axis device firmware version: [10.11.65]
- Stack trace or logs: 
/usr/bin/acap_runtime: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.34' not found (required by /host/lib/liblarod.so.1)
- OS and version: [Ubuntu 20.04 LTS]

**Comment by mikaelli-axis** [comment]
Thanks for the report, we're looking into what is causing this. If possible, try falling back to FW 10.10 to see if this resolves the issue for you.

**Comment by axisvivek** [comment]
Thank you for suggesting the old firmware. It is working with AXIS OS 10.10.69.
