### ISSUE TITLE
Are "edge-tpu" optimized models referenced in sample projects compatible with aarch64/ARTPEC8-based cameras?

### ISSUE THREAD

**Issue by jooshal** [AxisCommunications/acap-computer-vision-sdk-examples#34]
### Describe the bug

An app based on the sample project "object-detector-cpp" is not able to initialize an inference-server when an "edge-tpu optimized" SSD model is enabled by the app in an aarch64 camera (Axis Q1656). No other changes are made either to the original code files or Docker files besides changing the reference to the utilized model. It's not entirely clear from the documentation whether or not these kind of models are compatible with this aarch64 SoC (ARTPEC8).

### To reproduce

Change the model path on this line https://github.com/AxisCommunications/acap-computer-vision-sdk-examples/blob/bafec5b2f708fd2f9fecf3749bf5947194c061d6/object-detector-cpp/config/env.aarch64.artpec8#L1 to an edgetpu-optimized model, e.g., _ssd_mobilenet_v2_coco_quant_postprocess_edgetpu.tflite_ which is originally referenced here https://github.com/AxisCommunications/acap-computer-vision-sdk-examples/blob/bafec5b2f708fd2f9fecf3749bf5947194c061d6/object-detector-cpp/Dockerfile.model#L20

Otherwise follow the steps detailed in the tutorial's chapter "How to run the code" of the sample project "object-detector-cpp" while using arm64-specific variables. Testing was simplified by temporarily disabling TLS from the Docker daemon in the camera.

Specifically, the inference-server fails to utilize the provided edge-tpu model due to an error:

> inference-server_1  | ERROR in Inference: Failed to load model ssd_mobilenet_v2_coco_quant_postprocess_edgetpu.tflite (Could not load model: Could not set VX delegate)

Besides using an original Google/Coral SSD model (i.e., _ssd_mobilenet_v2_coco_quant_postprocess_edgetpu.tflite_), we also tried out our own custom model, optimized with an "Edge TPU Compiler" by Coral, but the end result was identical, the initialization of the inference server ended to the same delegation error. We kept the following command line unchanged, as we thought that the flag "-j 12" enables the accelerator chip, is this fine? https://github.com/AxisCommunications/acap-computer-vision-sdk-examples/blob/bafec5b2f708fd2f9fecf3749bf5947194c061d6/object-detector-cpp/config/env.aarch64.artpec8#L3

Is there a fundamental reason that these types of optimizations are not compatible with the aarch64, or specifically the ARTPEC8 SoC, or does this happen due to something missing from the firmware/Docker images?

The project's original configuration (from env.aarch64.artpec8) using the model _ssd_mobilenet_v2_coco_quant_postprocess.tflite_ did work fine in our tests for this camera (around 40ms per inference), however we would prefer to test and run models which are (fully?) optimized for the cameras on aarch64/ARTPEC8.

### Environment

- **Axis device model**: AXIS Q1656 Box Camera
- **Axis device firmware version**: 10.10.69
(Previously the firmware was 10.11.65 but we had to downgrade due to the "GLIBC not found" problem with it - see Issue #28)

- **Stack trace or logs**:
.....
Attaching to object-detector-cpp_acap_dl-models_1, object-detector-cpp_inference-server_1, object-detector-cpp_object-detector_1
acap_dl-models_1    | COPYRIGHT
acap_dl-models_1    | coco_labels.txt
acap_dl-models_1    | server.key
acap_dl-models_1    | server.pem
acap_dl-models_1    | ssd_mobilenet_v2_coco_quant_postprocess.tflite
acap_dl-models_1    | ssd_mobilenet_v2_coco_quant_postprocess_edgetpu.tflite
inference-server_1  | Server listening on 0.0.0.0:8501
object-detector-cpp_acap_dl-models_1 exited with code 0
object-detector_1   | Start: /usr/bin/objdetector /models/server.pem
object-detector_1   | Create memory mapped file
object-detector_1   | Caught frame  0 480x320
object-detector_1   | Connecting to: inference-server:8501
object-detector_1   | Waiting for response Z
inference-server_1  | ERROR in Inference: Failed to load model ssd_mobilenet_v2_coco_quant_postprocess_edgetpu.tflite (Could not load model: Could not set VX delegate)
object-detector_1   | gRPC call return code:
object-detector_1   | Capture: 22 ms
object-detector_1   | Inference grpc call: 227 ms
object-detector_1   | Postprocess: 0 ms
object-detector_1   |
object-detector_1   | Caught frame  1 480x320
object-detector_1   | Connecting to: inference-server:8501
object-detector_1   | Waiting for response Z
inference-server_1  | ERROR in Inference: Failed to load model ssd_mobilenet_v2_coco_quant_postprocess_edgetpu.tflite (Could not load model: Could not set VX delegate)
object-detector_1   | gRPC call return code:
.....

- **OS and version**: Ubuntu 20.04.4 LTS (Microsoft-WSL2 x86_64)

- **Version**: the sample project was pulled from the master branch of acap-computer-vision-sdk-examples(/object-detector-cpp), commit 636f437730a8f7eaff85cf9e2d064db8f069f2ab.

**Comment by mikaelli-axis** [comment]
The accelerator in ARTPEC8 is very different from the Edge TPU so hardware specific models are incompatible. For the Edge TPU you do off-line conversion using the edgetpu-tools while in ARTPEC8 the conversion is done by the camera as you're loading the model. There are training related differences as well that are at least partially covered in our tensorflow-to-larod-artpec8 example (https://github.com/AxisCommunications/acap-native-sdk-examples/tree/master/tensorflow-to-larod-artpec8).
