### ISSUE TITLE
does the docker container support seccomp and  apparmor feature?

### ISSUE THREAD

**Issue by pppaulpeter** [AxisCommunications/acap-computer-vision-sdk-examples#6]
Hi, 

this is not a issue, just a simple question, i still not get the newest axis camera that support the AI function.

**Comment by mikaelli-axis** [comment]
We have seccomp and apparmor support. Running "docker info" against Docker on the camera gives:
Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 3
 Server Version: dev
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 409c87ba59dd96965239573aa9458a3585c05468.m
 runc version: 249bca0a1316129dcd5bd38b5d75572274181cb5-dirty
 init version: de40ad0
 Security Options:
  **apparmor
  seccomp**
   Profile: default
 Kernel Version: 4.19.110-axis8
 Operating System: Axis (based on Poky from the Yocto Project) 10.7.3 (hardknott)
 OSType: linux
 Architecture: armv7l
 CPUs: 2
 Total Memory: 1.223GiB
 Name: axis-b8a44f191280
 ID: 3HWA:WMF5:YZAX:IWRP:W5RM:XN6U:6DNJ:NTG4:IFC6:KD3N:E6MB:PKSA
 Docker Root Dir: /var/spool/storage/SD_DISK/dockerd/data
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
