### ISSUE TITLE
"Error -1 getting parameter"

### ISSUE THREAD

**Issue by sheh** [AxisCommunications/acap-computer-vision-sdk-examples#74]
### Describe the bug

object-detector-python (tag v1.2.1) example fails with error:

```
...
Creating object-detector-python_inference-server_1       ... done
Attaching to object-detector-python_inference-server_1, object-detector-python_acap_dl-models_1, object-detector-python_object-detector-python_1
acap_dl-models_1          | COPYRIGHT
acap_dl-models_1          | coco_labels.txt
acap_dl-models_1          | ssd_mobilenet_v2_coco_quant_postprocess.tflite
acap_dl-models_1          | ssd_mobilenet_v2_coco_quant_postprocess_edgetpu.tflite
inference-server_1        | #Error -1 getting parameter 'root.Acapruntime.Verbose'!
inference-server_1        | #Error -1 getting parameter 'root.Acapruntime.IpPort'!
object-detector-python_acap_dl-models_1 exited with code 0
inference-server_1        | #Error -1 getting parameter 'root.Acapruntime.ChipId'!
object-detector-python_1  | object-detector-python connect to: unix:///tmp/acap-runtime.sock
...
```
Docker ACAP 1.2.3 is built from tag **1.2.3**.

### To reproduce

Install and run object-detector-python example according to the [steps](https://github.com/AxisCommunications/acap-computer-vision-sdk-examples/blob/main/object-detector-python/README.md).

### Environment

- Axis device model: Q3538-LVE
- Axis device firmware version: 10.11.65
- OS and version: Ubuntu 20.04 LTS

### Additional context

It is next step after #72 is fixed (Thanks!).

**Comment by Corallo** [comment]
Hello, we are aware of this error in the log, however this should not be a breaking error.
