### ISSUE TITLE
An issue when setup the environment for running a sample

### ISSUE THREAD

**Issue by rose-jinyang** [AxisCommunications/acap-computer-vision-sdk-examples#78]
Hello
How are you?
Thanks for contributing to this project.
I tried to run the sample "minimal-ml-inference" on my AXIS camera device.
I followed the below steps on Ubuntu 20.04 desktop as README.

export ARCH=armv7hf
export CHIP=tpu

export AXIS_TARGET_IP=x.x.x.x
export DOCKER_PORT=2376
docker --tlsverify -H tcp://$AXIS_TARGET_IP:$DOCKER_PORT system prune -af

But I met the following issue
unable to resolve docker endpoint: open /home/osboxes/.docker/ca.pem: no such file or directory

Where and how should I generate ca.pem file?

**Comment by Corallo** [comment]
Hello @rose-jinyang 
Please use the discussion page to ask questions if you need extra instructions using the examples.
We have already a discussion thread going on [here](https://github.com/AxisCommunications/acap-computer-vision-sdk-examples/discussions/76).

I'm going to close this issue as it is not a bug.
